
CXXFLAGS := -std=c++14 -pthread

#BINS := thread_2_1_1 \
#	ch2_3_spawn_threads
BINS :=\
	ch5_consume \
	ch5_rel_5_3_3 \
	ch5_fence_5_3_5 \
	ch5_listing_5.5 \
	ch5_listing_5.6 \
	ch5_listing_5.9 \
	ch5_listing_5.11 \
	ch5_listing_5.12

.PHONY: all
all: $(BINS)

.PHONY: clean
clean:
	rm -rf $(BINS) *~
